"""Companion code for Harness Engineering for Production AI Systems."""

from harness.audit import QUESTIONS, Area, AuditResult, Citation, Question, run_audit
from harness.boundary import (
    Context,
    Control,
    Locus,
    Origin,
    Span,
    audit_boundary,
)
from harness.errors import (
    BoundExceeded,
    HarnessError,
    NotACitation,
    OpenLoopError,
    Refused,
)
from harness.roles import (
    Bound,
    ClosureDefect,
    Comparator,
    Decision,
    Disposition,
    Gate,
    Harness,
    HarnessRegistry,
    Role,
    Sensor,
    Verdict,
)
from harness.state import (
    Budget,
    GateRecord,
    Mode,
    Proposal,
    RunContext,
    RunState,
)

__all__ = [
    "audit_boundary",
    "Span",
    "Origin",
    "Locus",
    "Control",
    "Context",
    "QUESTIONS",
    "Area",
    "AuditResult",
    "Bound",
    "Budget",
    "Citation",
    "ClosureDefect",
    "Comparator",
    "Decision",
    "Disposition",
    "Gate",
    "GateRecord",
    "Harness",
    "HarnessError",
    "HarnessRegistry",
    "Mode",
    "NotACitation",
    "OpenLoopError",
    "Proposal",
    "Question",
    "Refused",
    "Role",
    "RunContext",
    "RunState",
    "Sensor",
    "Verdict",
    "BoundExceeded",
    "run_audit",
]
